# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgb_webcontract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_manager_fullname', models.CharField(max_length=200)),
                ('it_manager_position', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgb_webcontract.Department'),
        ),
        migrations.AddField(
            model_name='contract',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgb_webcontract.Request'),
        ),
    ]
