# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgb_webcontract', '0002_auto_20161128_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='it_manager_email',
            field=models.EmailField(default='test@mail.ru', max_length=254),
            preserve_default=False,
        ),
    ]
