# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgb_webcontract', '0004_auto_20161128_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='department_id',
        ),
        migrations.AddField(
            model_name='request',
            name='department_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='bgb_webcontract.Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='login',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='password',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
