# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgb_webcontract', '0007_auto_20161201_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgb_webcontract.Department', verbose_name='Факультет/Подразделение'),
        ),
    ]
