# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgb_webcontract', '0010_auto_20161201_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AlterField(
            model_name='request',
            name='rejection_reason',
            field=models.CharField(blank=True, default='Заявка не обработана', max_length=200),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
