# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО заявителя полностью')),
                ('contract_number', models.CharField(max_length=20, verbose_name='Номер договора')),
                ('date_begin', models.DateTimeField(verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания заявки')),
                ('comment', models.CharField(max_length=100, verbose_name='Комментарий оператора')),
            ],
        ),
    ]
